export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import "~/styles/globals.css";
import { NextAuthProvider } from "~/ui/auth/next-auth-provider";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-neutral-900 text-neutral-100">
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
